In [1]:
import pandas as pd 
import seaborn as sns 

print(pd.__version__)
print(sns.__version__)

2.1.4
0.12.2

In [2]:
iris = sns.load_dataset("iris")
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [8]:
iris.tail(3)

     sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [11]:
iris.shape

(150, 5)

In [12]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [13]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [18]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [19]:
type(iris['species'].value_counts())

pandas.core.series.Series

- Series 데이터 타입 : https://pandas.pydata.org/docs/reference/api/pandas.Series.html
  ## 데이터프레임 / 시리즈 배열 비교하기 차이점 중요

In [20]:
iris['species'].value_counts().index

Index(['setosa', 'versicolor', 'virginica'], dtype='object', name='species')

In [21]:
iris['species'].value_counts().array

<NumpyExtensionArray>
[50, 50, 50]
Length: 3, dtype: int64

In [ ]:
iris['species'].value_counts().array

In [22]:
iris['species'].value_counts().memory_usage()

48

In [25]:
df = iris.drop("species", axis=1)
df.head(1)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [26]:
iris.shape, df.shape

((150, 5), (150, 4))

In [28]:
df2 = iris.drop(['sepal_length', 'sepal_width'], axis=1)
df2.head(1)

   petal_length  petal_width species
0           1.4          0.2  setosa

In [29]:
iris.shape, df.shape, df2.shape

((150, 5), (150, 4), (150, 3))

In [31]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [33]:
df3 = iris.drop([0, 1, 2], axis=0)
df3.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
3           4.6          3.1           1.5          0.2  setosa

In [35]:
df3 = iris.drop([0, 1, 2], axis=0).reset_index(drop=True)
df3.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           4.6          3.1           1.5          0.2  setosa

In [34]:
iris.shape, df.shape, df2.shape, df3.shape

((150, 5), (150, 4), (150, 3), (147, 5))

# 파일 입출력

## 파일 내보내기

In [8]:
iris.to_csv("iris.csv")

In [9]:
iris.to_csv("iris2.csv", index=False) #인덱스 넘버링 없앰 0~어쩌구 없음

In [10]:
iris.to_csv("./test_data/iris.csv", index=False) #test_data는 가상 폴더 ->

OSError: Cannot save file into a non-existent directory: 'test_data'

## 파일 불러오기

In [5]:
iris_df = pd.read_csv("./test_data/iris.csv")
iris_df.head(1)

FileNotFoundError: [Errno 2] No such file or directory: './test_data/iris.csv'

In [4]:
DATA_PATH = './kaggle/playground-series-s4e7/train.csv'

train = pd.read_csv(DATA_PATH)
train.head(1)

FileNotFoundError: [Errno 2] No such file or directory: './kaggle/playground-series-s4e7/train.csv'

In [42]:
DATA_PATH = './kaggle/playground-series-s4e7/'

train = pd.read_csv(DATA_PATH + 'train.csv')
train.head(1)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,0,Male,21,1,35.0,0,1-2 Year,Yes,65101.0,124.0,187,0

In [43]:
test = pd.read_csv(DATA_PATH + 'test.csv')
test.head(1)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage
0,11504798,Female,20,1,47.0,0,< 1 Year,No,2630.0,160.0,228

In [44]:
submission = pd.read_csv(DATA_PATH + 'sample_submission.csv')
submission.head(1)

         id  Response
0  11504798       0.5

## iloc vs loc 차이
- 강사 왈 : 일단은 loc만 기억하자!! (이유 : 직관적임)

In [48]:
# iris.loc[행, 열]
iris.loc[:, ['sepal_length', 'species']].head(1)

   sepal_length species
0           5.1  setosa

In [50]:
cols = ['sepal_length', 'species']
iris.loc[:, cols].head(1)

   sepal_length species
0           5.1  setosa

In [55]:
iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [58]:
cols = ['sepal_length', 'petal_length', 'species']
iris.loc[iris['petal_length'] >= 1.55, cols].head(1)

   sepal_length  petal_length species
5           5.4           1.7  setosa

### 문제 1. 
- petal_length가 1.7이상 인 값을 조회하고, 필드명은 sepal_width, petal_length만 추출하세요

In [61]:
cols = ['sepal_width', 'petal_length']
result = iris.loc[iris['petal_length'] >= 1.7, cols].reset_index(drop=True)
result

     sepal_width  petal_length
0            3.9           1.7
1            3.8           1.7
2            3.4           1.7
3            3.3           1.7
4            3.4           1.9
..           ...           ...
101          3.0           5.2
102          2.5           5.0
103          3.0           5.2
104          3.4           5.4
105          3.0           5.1

[106 rows x 2 columns]

## 다중조건
- AND 연산자 : 교집합, &
- OR 연산자 : 합집합, |

In [ ]:
cols = ['sepal_width', 'petal_length']
result = iris.loc[(조건1) & (조건2), cols].reset_index(drop=True)
result

In [65]:
result1 = iris.loc[iris['species'] == 'setosa']
result2 = result1.loc[iris['sepal_length'] <= 5.1]
result2.shape

(36, 5)

In [67]:
cols = ['sepal_width', 'petal_length']
result = iris.loc[(iris['species'] == 'setosa') & (iris['sepal_length'] <= 5.1), cols].reset_index(drop=True)
result.shape

(36, 2)

In [71]:
cols = ['sepal_width', 'petal_length']
result = iris.loc[(iris['species'] == 'setosa') &
                  (iris['sepal_length'] <= 5.1), cols].reset_index(drop=True)
result.shape

(36, 2)

In [72]:
train.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,0,Male,21,1,35.0,0,1-2 Year,Yes,65101.0,124.0,187,0
1,1,Male,43,1,28.0,0,> 2 Years,Yes,58911.0,26.0,288,1
2,2,Female,25,1,14.0,1,< 1 Year,No,38043.0,152.0,254,0
3,3,Female,35,1,1.0,0,1-2 Year,Yes,2630.0,156.0,76,0
4,4,Female,36,1,15.0,1,1-2 Year,No,31951.0,152.0,294,0

### 테스트 1. 
- Gender가 Male인 것만 조회하고, 전체 행의 갯수는?

In [74]:
# train.loc[행, 열]
train.loc[:, :].head(1)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,0,Male,21,1,35.0,0,1-2 Year,Yes,65101.0,124.0,187,0

In [78]:
test = (6228134, 12)
test[0]

6228134

In [79]:
# 데이터프레임 => tuple => int
train.loc[train['Gender'] == 'Male', :].shape[0]

6228134

### 문제 2. 
- Vehicle_Age가 1-2 Year과 < 1 Year만 추출
- isin() 연산자 활용

In [82]:
train['Vehicle_Age'].value_counts()

Vehicle_Age
1-2 Year     5982678
< 1 Year     5044145
> 2 Years     477975
Name: count, dtype: int64

In [85]:
s = pd.Series(['llama', 'cow', 'llama', 'beetle', 'llama',
               'hippo'], name='animal')
s.value_counts()

animal
llama     3
cow       1
beetle    1
hippo     1
Name: count, dtype: int64

In [86]:
s.isin(['cow', 'llama'])

0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [89]:
Vehicle_Age_Values = ['1-2 Year', '< 1 Year']
train.loc[train['Vehicle_Age'].isin(Vehicle_Age_Values), :].shape

(11026823, 12)